// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: marketplace_common/marketplace_common.proto

package marketplace_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_NEW              Status = 0
	Status_PARTIALLY_FILLED Status = 1
	Status_REJECTED         Status = 2
	Status_COMPLETE         Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "NEW",
		1: "PARTIALLY_FILLED",
		2: "REJECTED",
		3: "COMPLETE",
	}
	Status_value = map[string]int32{
		"NEW":              0,
		"PARTIALLY_FILLED": 1,
		"REJECTED":         2,
		"COMPLETE":         3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_marketplace_common_marketplace_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_marketplace_common_marketplace_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_marketplace_common_marketplace_common_proto_rawDescGZIP(), []int{0}
}

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtworkId uint32 `protobuf:"varint,2,opt,name=artwork_id,json=artworkId,proto3" json:"artwork_id,omitempty"`
	BidderId  uint32 `protobuf:"varint,3,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Quantity  uint32 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price     uint32 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_common_marketplace_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_common_marketplace_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_marketplace_common_marketplace_common_proto_rawDescGZIP(), []int{0}
}

func (x *Bid) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bid) GetArtworkId() uint32 {
	if x != nil {
		return x.ArtworkId
	}
	return 0
}

func (x *Bid) GetBidderId() uint32 {
	if x != nil {
		return x.BidderId
	}
	return 0
}

func (x *Bid) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Bid) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Ask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtworkId uint32 `protobuf:"varint,2,opt,name=artwork_id,json=artworkId,proto3" json:"artwork_id,omitempty"`
	AskerId   uint32 `protobuf:"varint,3,opt,name=asker_id,json=askerId,proto3" json:"asker_id,omitempty"`
	Quantity  uint32 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price     uint32 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Ask) Reset() {
	*x = Ask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_common_marketplace_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ask) ProtoMessage() {}

func (x *Ask) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_common_marketplace_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ask.ProtoReflect.Descriptor instead.
func (*Ask) Descriptor() ([]byte, []int) {
	return file_marketplace_common_marketplace_common_proto_rawDescGZIP(), []int{1}
}

func (x *Ask) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ask) GetArtworkId() uint32 {
	if x != nil {
		return x.ArtworkId
	}
	return 0
}

func (x *Ask) GetAskerId() uint32 {
	if x != nil {
		return x.AskerId
	}
	return 0
}

func (x *Ask) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Ask) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidId          uint32 `protobuf:"varint,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	AskId          uint32 `protobuf:"varint,2,opt,name=ask_id,json=askId,proto3" json:"ask_id,omitempty"`
	ArtworkId      uint32 `protobuf:"varint,3,opt,name=artwork_id,json=artworkId,proto3" json:"artwork_id,omitempty"`
	Price          uint32 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	QuantityFilled uint32 `protobuf:"varint,5,opt,name=quantity_filled,json=quantityFilled,proto3" json:"quantity_filled,omitempty"`
	Status         uint32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_common_marketplace_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_common_marketplace_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_marketplace_common_marketplace_common_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetBidId() uint32 {
	if x != nil {
		return x.BidId
	}
	return 0
}

func (x *Order) GetAskId() uint32 {
	if x != nil {
		return x.AskId
	}
	return 0
}

func (x *Order) GetArtworkId() uint32 {
	if x != nil {
		return x.ArtworkId
	}
	return 0
}

func (x *Order) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetQuantityFilled() uint32 {
	if x != nil {
		return x.QuantityFilled
	}
	return 0
}

func (x *Order) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BidStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid            *Bid   `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	QuantityFilled uint32 `protobuf:"varint,2,opt,name=quantity_filled,json=quantityFilled,proto3" json:"quantity_filled,omitempty"`
	Status         Status `protobuf:"varint,3,opt,name=status,proto3,enum=marketplace_common.Status" json:"status,omitempty"`
}

func (x *BidStatus) Reset() {
	*x = BidStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_common_marketplace_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidStatus) ProtoMessage() {}

func (x *BidStatus) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_common_marketplace_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidStatus.ProtoReflect.Descriptor instead.
func (*BidStatus) Descriptor() ([]byte, []int) {
	return file_marketplace_common_marketplace_common_proto_rawDescGZIP(), []int{3}
}

func (x *BidStatus) GetBid() *Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *BidStatus) GetQuantityFilled() uint32 {
	if x != nil {
		return x.QuantityFilled
	}
	return 0
}

func (x *BidStatus) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_NEW
}

type AskStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ask            *Ask   `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
	QuantityFilled uint32 `protobuf:"varint,2,opt,name=quantity_filled,json=quantityFilled,proto3" json:"quantity_filled,omitempty"`
	Status         Status `protobuf:"varint,3,opt,name=status,proto3,enum=marketplace_common.Status" json:"status,omitempty"`
}

func (x *AskStatus) Reset() {
	*x = AskStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_common_marketplace_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskStatus) ProtoMessage() {}

func (x *AskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_common_marketplace_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskStatus.ProtoReflect.Descriptor instead.
func (*AskStatus) Descriptor() ([]byte, []int) {
	return file_marketplace_common_marketplace_common_proto_rawDescGZIP(), []int{4}
}

func (x *AskStatus) GetAsk() *Ask {
	if x != nil {
		return x.Ask
	}
	return nil
}

func (x *AskStatus) GetQuantityFilled() uint32 {
	if x != nil {
		return x.QuantityFilled
	}
	return 0
}

func (x *AskStatus) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_NEW
}

var File_marketplace_common_marketplace_common_proto protoreflect.FileDescriptor

var file_marketplace_common_marketplace_common_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x22, 0x83, 0x01, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61,
	0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x69, 0x64,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x03, 0x41, 0x73, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x05,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x69, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x69, 0x64, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x69, 0x6c, 0x6c, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x09, 0x42, 0x69,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x03, 0x62,
	0x69, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x93, 0x01, 0x0a, 0x09, 0x41, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a,
	0x03, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x41, 0x73, 0x6b, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x69, 0x6c, 0x6c, 0x65,
	0x64, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x43, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x52, 0x54,
	0x49, 0x41, 0x4c, 0x4c, 0x59, 0x5f, 0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x69, 0x64, 0x64, 0x2f, 0x66,
	0x72, 0x61, 0x63, 0x74, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_marketplace_common_marketplace_common_proto_rawDescOnce sync.Once
	file_marketplace_common_marketplace_common_proto_rawDescData = file_marketplace_common_marketplace_common_proto_rawDesc
)

func file_marketplace_common_marketplace_common_proto_rawDescGZIP() []byte {
	file_marketplace_common_marketplace_common_proto_rawDescOnce.Do(func() {
		file_marketplace_common_marketplace_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_marketplace_common_marketplace_common_proto_rawDescData)
	})
	return file_marketplace_common_marketplace_common_proto_rawDescData
}

var file_marketplace_common_marketplace_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_marketplace_common_marketplace_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_marketplace_common_marketplace_common_proto_goTypes = []interface{}{
	(Status)(0),       // 0: marketplace_common.Status
	(*Bid)(nil),       // 1: marketplace_common.Bid
	(*Ask)(nil),       // 2: marketplace_common.Ask
	(*Order)(nil),     // 3: marketplace_common.Order
	(*BidStatus)(nil), // 4: marketplace_common.BidStatus
	(*AskStatus)(nil), // 5: marketplace_common.AskStatus
}
var file_marketplace_common_marketplace_common_proto_depIdxs = []int32{
	1, // 0: marketplace_common.BidStatus.bid:type_name -> marketplace_common.Bid
	0, // 1: marketplace_common.BidStatus.status:type_name -> marketplace_common.Status
	2, // 2: marketplace_common.AskStatus.ask:type_name -> marketplace_common.Ask
	0, // 3: marketplace_common.AskStatus.status:type_name -> marketplace_common.Status
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_marketplace_common_marketplace_common_proto_init() }
func file_marketplace_common_marketplace_common_proto_init() {
	if File_marketplace_common_marketplace_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marketplace_common_marketplace_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketplace_common_marketplace_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketplace_common_marketplace_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketplace_common_marketplace_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketplace_common_marketplace_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marketplace_common_marketplace_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_common_marketplace_common_proto_goTypes,
		DependencyIndexes: file_marketplace_common_marketplace_common_proto_depIdxs,
		EnumInfos:         file_marketplace_common_marketplace_common_proto_enumTypes,
		MessageInfos:      file_marketplace_common_marketplace_common_proto_msgTypes,
	}.Build()
	File_marketplace_common_marketplace_common_proto = out.File
	file_marketplace_common_marketplace_common_proto_rawDesc = nil
	file_marketplace_common_marketplace_common_proto_goTypes = nil
	file_marketplace_common_marketplace_common_proto_depIdxs = nil
}
