// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: marketplace_common/marketplace_common.proto

package marketplace_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtworkId uint32 `protobuf:"varint,2,opt,name=artwork_id,json=artworkId,proto3" json:"artwork_id,omitempty"`
	BidderId  uint32 `protobuf:"varint,3,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Quantity  uint32 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price     uint32 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_common_marketplace_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_common_marketplace_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_marketplace_common_marketplace_common_proto_rawDescGZIP(), []int{0}
}

func (x *Bid) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bid) GetArtworkId() uint32 {
	if x != nil {
		return x.ArtworkId
	}
	return 0
}

func (x *Bid) GetBidderId() uint32 {
	if x != nil {
		return x.BidderId
	}
	return 0
}

func (x *Bid) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Bid) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_marketplace_common_marketplace_common_proto protoreflect.FileDescriptor

var file_marketplace_common_marketplace_common_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x22, 0x83, 0x01, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61,
	0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x69, 0x64,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x69, 0x64, 0x64, 0x2f, 0x66, 0x72, 0x61, 0x63,
	0x74, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_marketplace_common_marketplace_common_proto_rawDescOnce sync.Once
	file_marketplace_common_marketplace_common_proto_rawDescData = file_marketplace_common_marketplace_common_proto_rawDesc
)

func file_marketplace_common_marketplace_common_proto_rawDescGZIP() []byte {
	file_marketplace_common_marketplace_common_proto_rawDescOnce.Do(func() {
		file_marketplace_common_marketplace_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_marketplace_common_marketplace_common_proto_rawDescData)
	})
	return file_marketplace_common_marketplace_common_proto_rawDescData
}

var file_marketplace_common_marketplace_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_marketplace_common_marketplace_common_proto_goTypes = []interface{}{
	(*Bid)(nil), // 0: marketplace_common.Bid
}
var file_marketplace_common_marketplace_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketplace_common_marketplace_common_proto_init() }
func file_marketplace_common_marketplace_common_proto_init() {
	if File_marketplace_common_marketplace_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marketplace_common_marketplace_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marketplace_common_marketplace_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_common_marketplace_common_proto_goTypes,
		DependencyIndexes: file_marketplace_common_marketplace_common_proto_depIdxs,
		MessageInfos:      file_marketplace_common_marketplace_common_proto_msgTypes,
	}.Build()
	File_marketplace_common_marketplace_common_proto = out.File
	file_marketplace_common_marketplace_common_proto_rawDesc = nil
	file_marketplace_common_marketplace_common_proto_goTypes = nil
	file_marketplace_common_marketplace_common_proto_depIdxs = nil
}
