// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: storage/storage.proto

package storage

import (
	marketplace_common "github.com/blidd/fractr-proto/marketplace_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidStatus_Status int32

const (
	BidStatus_NEW              BidStatus_Status = 0
	BidStatus_PARTIALLY_FILLED BidStatus_Status = 1
	BidStatus_REJECTED         BidStatus_Status = 2
	BidStatus_COMPLETE         BidStatus_Status = 3
)

// Enum value maps for BidStatus_Status.
var (
	BidStatus_Status_name = map[int32]string{
		0: "NEW",
		1: "PARTIALLY_FILLED",
		2: "REJECTED",
		3: "COMPLETE",
	}
	BidStatus_Status_value = map[string]int32{
		"NEW":              0,
		"PARTIALLY_FILLED": 1,
		"REJECTED":         2,
		"COMPLETE":         3,
	}
)

func (x BidStatus_Status) Enum() *BidStatus_Status {
	p := new(BidStatus_Status)
	*p = x
	return p
}

func (x BidStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_storage_proto_enumTypes[0].Descriptor()
}

func (BidStatus_Status) Type() protoreflect.EnumType {
	return &file_storage_storage_proto_enumTypes[0]
}

func (x BidStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidStatus_Status.Descriptor instead.
func (BidStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4, 0}
}

type AskStatus_Status int32

const (
	AskStatus_NEW              AskStatus_Status = 0
	AskStatus_PARTIALLY_FILLED AskStatus_Status = 1
	AskStatus_REJECTED         AskStatus_Status = 2
	AskStatus_COMPLETE         AskStatus_Status = 3
)

// Enum value maps for AskStatus_Status.
var (
	AskStatus_Status_name = map[int32]string{
		0: "NEW",
		1: "PARTIALLY_FILLED",
		2: "REJECTED",
		3: "COMPLETE",
	}
	AskStatus_Status_value = map[string]int32{
		"NEW":              0,
		"PARTIALLY_FILLED": 1,
		"REJECTED":         2,
		"COMPLETE":         3,
	}
)

func (x AskStatus_Status) Enum() *AskStatus_Status {
	p := new(AskStatus_Status)
	*p = x
	return p
}

func (x AskStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AskStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_storage_proto_enumTypes[1].Descriptor()
}

func (AskStatus_Status) Type() protoreflect.EnumType {
	return &file_storage_storage_proto_enumTypes[1]
}

func (x AskStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AskStatus_Status.Descriptor instead.
func (AskStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{5, 0}
}

type GetRequest_Type int32

const (
	GetRequest_ARTWORK  GetRequest_Type = 0
	GetRequest_BID      GetRequest_Type = 1
	GetRequest_ASK      GetRequest_Type = 2
	GetRequest_USERBIDS GetRequest_Type = 3
	GetRequest_USERASKS GetRequest_Type = 4
)

// Enum value maps for GetRequest_Type.
var (
	GetRequest_Type_name = map[int32]string{
		0: "ARTWORK",
		1: "BID",
		2: "ASK",
		3: "USERBIDS",
		4: "USERASKS",
	}
	GetRequest_Type_value = map[string]int32{
		"ARTWORK":  0,
		"BID":      1,
		"ASK":      2,
		"USERBIDS": 3,
		"USERASKS": 4,
	}
)

func (x GetRequest_Type) Enum() *GetRequest_Type {
	p := new(GetRequest_Type)
	*p = x
	return p
}

func (x GetRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_storage_proto_enumTypes[2].Descriptor()
}

func (GetRequest_Type) Type() protoreflect.EnumType {
	return &file_storage_storage_proto_enumTypes[2]
}

func (x GetRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetRequest_Type.Descriptor instead.
func (GetRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{6, 0}
}

type GetResponse_Type int32

const (
	GetResponse_ARTWORK     GetResponse_Type = 0
	GetResponse_BID         GetResponse_Type = 1
	GetResponse_ASK         GetResponse_Type = 2
	GetResponse_USERBIDS    GetResponse_Type = 3
	GetResponse_USERASKS    GetResponse_Type = 4
	GetResponse_USERPROFILE GetResponse_Type = 5
)

// Enum value maps for GetResponse_Type.
var (
	GetResponse_Type_name = map[int32]string{
		0: "ARTWORK",
		1: "BID",
		2: "ASK",
		3: "USERBIDS",
		4: "USERASKS",
		5: "USERPROFILE",
	}
	GetResponse_Type_value = map[string]int32{
		"ARTWORK":     0,
		"BID":         1,
		"ASK":         2,
		"USERBIDS":    3,
		"USERASKS":    4,
		"USERPROFILE": 5,
	}
)

func (x GetResponse_Type) Enum() *GetResponse_Type {
	p := new(GetResponse_Type)
	*p = x
	return p
}

func (x GetResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_storage_proto_enumTypes[3].Descriptor()
}

func (GetResponse_Type) Type() protoreflect.EnumType {
	return &file_storage_storage_proto_enumTypes[3]
}

func (x GetResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetResponse_Type.Descriptor instead.
func (GetResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{7, 0}
}

type PutRequest_Type int32

const (
	PutRequest_ARTWORK     PutRequest_Type = 0
	PutRequest_BID         PutRequest_Type = 1
	PutRequest_ASK         PutRequest_Type = 2
	PutRequest_USERBIDS    PutRequest_Type = 3
	PutRequest_USERASKS    PutRequest_Type = 4
	PutRequest_USERPROFILE PutRequest_Type = 5
)

// Enum value maps for PutRequest_Type.
var (
	PutRequest_Type_name = map[int32]string{
		0: "ARTWORK",
		1: "BID",
		2: "ASK",
		3: "USERBIDS",
		4: "USERASKS",
		5: "USERPROFILE",
	}
	PutRequest_Type_value = map[string]int32{
		"ARTWORK":     0,
		"BID":         1,
		"ASK":         2,
		"USERBIDS":    3,
		"USERASKS":    4,
		"USERPROFILE": 5,
	}
)

func (x PutRequest_Type) Enum() *PutRequest_Type {
	p := new(PutRequest_Type)
	*p = x
	return p
}

func (x PutRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_storage_proto_enumTypes[4].Descriptor()
}

func (PutRequest_Type) Type() protoreflect.EnumType {
	return &file_storage_storage_proto_enumTypes[4]
}

func (x PutRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutRequest_Type.Descriptor instead.
func (PutRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{8, 0}
}

type DeleteRequest_Type int32

const (
	DeleteRequest_ARTWORK     DeleteRequest_Type = 0
	DeleteRequest_BID         DeleteRequest_Type = 1
	DeleteRequest_ASK         DeleteRequest_Type = 2
	DeleteRequest_USERBIDS    DeleteRequest_Type = 3
	DeleteRequest_USERASKS    DeleteRequest_Type = 4
	DeleteRequest_USERPROFILE DeleteRequest_Type = 5
)

// Enum value maps for DeleteRequest_Type.
var (
	DeleteRequest_Type_name = map[int32]string{
		0: "ARTWORK",
		1: "BID",
		2: "ASK",
		3: "USERBIDS",
		4: "USERASKS",
		5: "USERPROFILE",
	}
	DeleteRequest_Type_value = map[string]int32{
		"ARTWORK":     0,
		"BID":         1,
		"ASK":         2,
		"USERBIDS":    3,
		"USERASKS":    4,
		"USERPROFILE": 5,
	}
)

func (x DeleteRequest_Type) Enum() *DeleteRequest_Type {
	p := new(DeleteRequest_Type)
	*p = x
	return p
}

func (x DeleteRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_storage_proto_enumTypes[5].Descriptor()
}

func (DeleteRequest_Type) Type() protoreflect.EnumType {
	return &file_storage_storage_proto_enumTypes[5]
}

func (x DeleteRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteRequest_Type.Descriptor instead.
func (DeleteRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{10, 0}
}

type Artist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName   string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Artist) Reset() {
	*x = Artist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Artist) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Artist) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Artist) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Artist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Artwork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Artist   *Artist                   `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Name     string                    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnerIds []uint32                  `protobuf:"varint,4,rep,packed,name=owner_ids,json=ownerIds,proto3" json:"owner_ids,omitempty"`
	Bids     []*marketplace_common.Bid `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks     []*marketplace_common.Ask `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
}

func (x *Artwork) Reset() {
	*x = Artwork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artwork) ProtoMessage() {}

func (x *Artwork) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artwork.ProtoReflect.Descriptor instead.
func (*Artwork) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Artwork) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Artwork) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *Artwork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artwork) GetOwnerIds() []uint32 {
	if x != nil {
		return x.OwnerIds
	}
	return nil
}

func (x *Artwork) GetBids() []*marketplace_common.Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Artwork) GetAsks() []*marketplace_common.Ask {
	if x != nil {
		return x.Asks
	}
	return nil
}

type Shard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtworkId uint32   `protobuf:"varint,1,opt,name=artwork_id,json=artworkId,proto3" json:"artwork_id,omitempty"`
	OwnerId   uint32   `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TokenIds  []uint32 `protobuf:"varint,3,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
}

func (x *Shard) Reset() {
	*x = Shard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Shard) GetArtworkId() uint32 {
	if x != nil {
		return x.ArtworkId
	}
	return 0
}

func (x *Shard) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Shard) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint32                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsArtist    bool                      `protobuf:"varint,2,opt,name=is_artist,json=isArtist,proto3" json:"is_artist,omitempty"`
	CurrentBids []*marketplace_common.Bid `protobuf:"bytes,3,rep,name=current_bids,json=currentBids,proto3" json:"current_bids,omitempty"`
	CurrentAsks []*marketplace_common.Ask `protobuf:"bytes,4,rep,name=current_asks,json=currentAsks,proto3" json:"current_asks,omitempty"`
	OwnedShards []*Shard                  `protobuf:"bytes,5,rep,name=owned_shards,json=ownedShards,proto3" json:"owned_shards,omitempty"`
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *UserProfile) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetIsArtist() bool {
	if x != nil {
		return x.IsArtist
	}
	return false
}

func (x *UserProfile) GetCurrentBids() []*marketplace_common.Bid {
	if x != nil {
		return x.CurrentBids
	}
	return nil
}

func (x *UserProfile) GetCurrentAsks() []*marketplace_common.Ask {
	if x != nil {
		return x.CurrentAsks
	}
	return nil
}

func (x *UserProfile) GetOwnedShards() []*Shard {
	if x != nil {
		return x.OwnedShards
	}
	return nil
}

type BidStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid            *marketplace_common.Bid `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	QuantityFilled uint32                  `protobuf:"varint,2,opt,name=quantity_filled,json=quantityFilled,proto3" json:"quantity_filled,omitempty"`
}

func (x *BidStatus) Reset() {
	*x = BidStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidStatus) ProtoMessage() {}

func (x *BidStatus) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidStatus.ProtoReflect.Descriptor instead.
func (*BidStatus) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *BidStatus) GetBid() *marketplace_common.Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *BidStatus) GetQuantityFilled() uint32 {
	if x != nil {
		return x.QuantityFilled
	}
	return 0
}

type AskStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ask            *marketplace_common.Ask `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
	QuantityFilled uint32                  `protobuf:"varint,2,opt,name=quantity_filled,json=quantityFilled,proto3" json:"quantity_filled,omitempty"`
}

func (x *AskStatus) Reset() {
	*x = AskStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskStatus) ProtoMessage() {}

func (x *AskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskStatus.ProtoReflect.Descriptor instead.
func (*AskStatus) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{5}
}

func (x *AskStatus) GetAsk() *marketplace_common.Ask {
	if x != nil {
		return x.Ask
	}
	return nil
}

func (x *AskStatus) GetQuantityFilled() uint32 {
	if x != nil {
		return x.QuantityFilled
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *uint32  `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                            // optional field
	UserIds       []uint32 `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`                  // optional field
	PrimaryMarket *bool    `protobuf:"varint,3,opt,name=primary_market,json=primaryMarket,proto3,oneof" json:"primary_market,omitempty"` // optional field
	ArtistName    *string  `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3,oneof" json:"artist_name,omitempty"`           // optional field
	ArtTitle      *string  `protobuf:"bytes,5,opt,name=art_title,json=artTitle,proto3,oneof" json:"art_title,omitempty"`                 // optional field
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetRequest) GetUserIds() []uint32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetRequest) GetPrimaryMarket() bool {
	if x != nil && x.PrimaryMarket != nil {
		return *x.PrimaryMarket
	}
	return false
}

func (x *GetRequest) GetArtistName() string {
	if x != nil && x.ArtistName != nil {
		return *x.ArtistName
	}
	return ""
}

func (x *GetRequest) GetArtTitle() string {
	if x != nil && x.ArtTitle != nil {
		return *x.ArtTitle
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artworks  []*Artwork   `protobuf:"bytes,1,rep,name=artworks,proto3" json:"artworks,omitempty"`
	Profile   *UserProfile `protobuf:"bytes,2,opt,name=profile,proto3,oneof" json:"profile,omitempty"`
	BidStatus []*BidStatus `protobuf:"bytes,3,rep,name=bidStatus,proto3" json:"bidStatus,omitempty"`
	AskStatus []*AskStatus `protobuf:"bytes,4,rep,name=askStatus,proto3" json:"askStatus,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetArtworks() []*Artwork {
	if x != nil {
		return x.Artworks
	}
	return nil
}

func (x *GetResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetResponse) GetBidStatus() []*BidStatus {
	if x != nil {
		return x.BidStatus
	}
	return nil
}

func (x *GetResponse) GetAskStatus() []*AskStatus {
	if x != nil {
		return x.AskStatus
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *uint32  `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                            // optional field
	UserIds       []uint32 `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`                  // optional field
	PrimaryMarket *bool    `protobuf:"varint,3,opt,name=primary_market,json=primaryMarket,proto3,oneof" json:"primary_market,omitempty"` // optional field
	ArtistName    *string  `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3,oneof" json:"artist_name,omitempty"`           // optional field
	ArtTitle      *string  `protobuf:"bytes,5,opt,name=art_title,json=artTitle,proto3,oneof" json:"art_title,omitempty"`                 // optional field
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{8}
}

func (x *PutRequest) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PutRequest) GetUserIds() []uint32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PutRequest) GetPrimaryMarket() bool {
	if x != nil && x.PrimaryMarket != nil {
		return *x.PrimaryMarket
	}
	return false
}

func (x *PutRequest) GetArtistName() string {
	if x != nil && x.ArtistName != nil {
		return *x.ArtistName
	}
	return ""
}

func (x *PutRequest) GetArtTitle() string {
	if x != nil && x.ArtTitle != nil {
		return *x.ArtTitle
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{9}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *uint32  `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                            // optional field
	UserIds       []uint32 `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`                  // optional field
	PrimaryMarket *bool    `protobuf:"varint,3,opt,name=primary_market,json=primaryMarket,proto3,oneof" json:"primary_market,omitempty"` // optional field
	ArtistName    *string  `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3,oneof" json:"artist_name,omitempty"`           // optional field
	ArtTitle      *string  `protobuf:"bytes,5,opt,name=art_title,json=artTitle,proto3,oneof" json:"art_title,omitempty"`                 // optional field
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *DeleteRequest) GetUserIds() []uint32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *DeleteRequest) GetPrimaryMarket() bool {
	if x != nil && x.PrimaryMarket != nil {
		return *x.PrimaryMarket
	}
	return false
}

func (x *DeleteRequest) GetArtistName() string {
	if x != nil && x.ArtistName != nil {
		return *x.ArtistName
	}
	return ""
}

func (x *DeleteRequest) GetArtTitle() string {
	if x != nil && x.ArtTitle != nil {
		return *x.ArtTitle
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_storage_storage_proto protoreflect.FileDescriptor

var file_storage_storage_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x1a, 0x2b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a,
	0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xcd, 0x01, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x62,
	0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42,
	0x69, 0x64, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x73, 0x6b, 0x52,
	0x04, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x5e, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x49, 0x64, 0x73, 0x22, 0xee, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x42, 0x69, 0x64, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x41, 0x73, 0x6b, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41,
	0x73, 0x6b, 0x73, 0x12, 0x31, 0x0a, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x5f, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x64,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x09, 0x42, 0x69, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x6c,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0x43, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50,
	0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x4c, 0x59, 0x5f, 0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x22, 0xa4, 0x01,
	0x0a, 0x09, 0x41, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x03, 0x61,
	0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x73,
	0x6b, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0e, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x22,
	0x43, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x4c, 0x59, 0x5f,
	0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45,
	0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x10, 0x03, 0x22, 0xab, 0x02, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x0d, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x24, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x08, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x22, 0x41, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x41, 0x52, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x4b, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x42, 0x49, 0x44, 0x53, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08,
	0x55, 0x53, 0x45, 0x52, 0x41, 0x53, 0x4b, 0x53, 0x10, 0x04, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69,
	0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x22, 0xb4, 0x02, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41,
	0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x08, 0x61, 0x72, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x12, 0x33, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x42, 0x69, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x62, 0x69,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x61, 0x73, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x52, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x52, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x4b, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x42, 0x49, 0x44, 0x53, 0x10, 0x03, 0x12, 0x0c,
	0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x41, 0x53, 0x4b, 0x53, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x53, 0x45, 0x52, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x05, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0xbc, 0x02, 0x0a, 0x0a, 0x50, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x6d,
	0x61, 0x72, 0x79, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0a, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52,
	0x08, 0x61, 0x72, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x22, 0x52, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x52, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53,
	0x4b, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x42, 0x49, 0x44, 0x53, 0x10,
	0x03, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x41, 0x53, 0x4b, 0x53, 0x10, 0x04, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x53, 0x45, 0x52, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x05,
	0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x70, 0x72, 0x69, 0x6d,
	0x61, 0x72, 0x79, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0xbf, 0x02, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x0d, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x24, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x08, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x22, 0x52, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x41, 0x52, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x4b, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x42, 0x49, 0x44, 0x53, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08,
	0x55, 0x53, 0x45, 0x52, 0x41, 0x53, 0x4b, 0x53, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x53,
	0x45, 0x52, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x05, 0x42, 0x05, 0x0a, 0x03, 0x5f,
	0x69, 0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32,
	0xa8, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x03, 0x50, 0x75, 0x74, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x69, 0x64, 0x64, 0x2f, 0x66,
	0x72, 0x61, 0x63, 0x74, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_storage_proto_rawDescOnce sync.Once
	file_storage_storage_proto_rawDescData = file_storage_storage_proto_rawDesc
)

func file_storage_storage_proto_rawDescGZIP() []byte {
	file_storage_storage_proto_rawDescOnce.Do(func() {
		file_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_storage_proto_rawDescData)
	})
	return file_storage_storage_proto_rawDescData
}

var file_storage_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_storage_storage_proto_goTypes = []interface{}{
	(BidStatus_Status)(0),          // 0: storage.BidStatus.Status
	(AskStatus_Status)(0),          // 1: storage.AskStatus.Status
	(GetRequest_Type)(0),           // 2: storage.GetRequest.Type
	(GetResponse_Type)(0),          // 3: storage.GetResponse.Type
	(PutRequest_Type)(0),           // 4: storage.PutRequest.Type
	(DeleteRequest_Type)(0),        // 5: storage.DeleteRequest.Type
	(*Artist)(nil),                 // 6: storage.Artist
	(*Artwork)(nil),                // 7: storage.Artwork
	(*Shard)(nil),                  // 8: storage.Shard
	(*UserProfile)(nil),            // 9: storage.UserProfile
	(*BidStatus)(nil),              // 10: storage.BidStatus
	(*AskStatus)(nil),              // 11: storage.AskStatus
	(*GetRequest)(nil),             // 12: storage.GetRequest
	(*GetResponse)(nil),            // 13: storage.GetResponse
	(*PutRequest)(nil),             // 14: storage.PutRequest
	(*PutResponse)(nil),            // 15: storage.PutResponse
	(*DeleteRequest)(nil),          // 16: storage.DeleteRequest
	(*DeleteResponse)(nil),         // 17: storage.DeleteResponse
	(*marketplace_common.Bid)(nil), // 18: marketplace_common.Bid
	(*marketplace_common.Ask)(nil), // 19: marketplace_common.Ask
}
var file_storage_storage_proto_depIdxs = []int32{
	6,  // 0: storage.Artwork.artist:type_name -> storage.Artist
	18, // 1: storage.Artwork.bids:type_name -> marketplace_common.Bid
	19, // 2: storage.Artwork.asks:type_name -> marketplace_common.Ask
	18, // 3: storage.UserProfile.current_bids:type_name -> marketplace_common.Bid
	19, // 4: storage.UserProfile.current_asks:type_name -> marketplace_common.Ask
	8,  // 5: storage.UserProfile.owned_shards:type_name -> storage.Shard
	18, // 6: storage.BidStatus.bid:type_name -> marketplace_common.Bid
	19, // 7: storage.AskStatus.ask:type_name -> marketplace_common.Ask
	7,  // 8: storage.GetResponse.artworks:type_name -> storage.Artwork
	9,  // 9: storage.GetResponse.profile:type_name -> storage.UserProfile
	10, // 10: storage.GetResponse.bidStatus:type_name -> storage.BidStatus
	11, // 11: storage.GetResponse.askStatus:type_name -> storage.AskStatus
	12, // 12: storage.Service.Get:input_type -> storage.GetRequest
	14, // 13: storage.Service.Put:input_type -> storage.PutRequest
	16, // 14: storage.Service.Delete:input_type -> storage.DeleteRequest
	13, // 15: storage.Service.Get:output_type -> storage.GetResponse
	15, // 16: storage.Service.Put:output_type -> storage.PutResponse
	17, // 17: storage.Service.Delete:output_type -> storage.DeleteResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_storage_storage_proto_init() }
func file_storage_storage_proto_init() {
	if File_storage_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artwork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_storage_storage_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_storage_storage_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_storage_storage_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_storage_storage_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_storage_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_storage_proto_goTypes,
		DependencyIndexes: file_storage_storage_proto_depIdxs,
		EnumInfos:         file_storage_storage_proto_enumTypes,
		MessageInfos:      file_storage_storage_proto_msgTypes,
	}.Build()
	File_storage_storage_proto = out.File
	file_storage_storage_proto_rawDesc = nil
	file_storage_storage_proto_goTypes = nil
	file_storage_storage_proto_depIdxs = nil
}
