// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: marketplace_secondary/marketplace_secondary.proto

package marketplace_secondary

import (
	marketplace_common "github.com/blidd/fractr-proto/marketplace_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceBidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid *marketplace_common.Bid `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_secondary_marketplace_secondary_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceBidRequest) GetBid() *marketplace_common.Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type PlaceBidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidStatus *marketplace_common.BidStatus `protobuf:"bytes,1,opt,name=bid_status,json=bidStatus,proto3" json:"bid_status,omitempty"`
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_secondary_marketplace_secondary_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBidResponse) GetBidStatus() *marketplace_common.BidStatus {
	if x != nil {
		return x.BidStatus
	}
	return nil
}

type PlaceAskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ask *marketplace_common.Ask `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
}

func (x *PlaceAskRequest) Reset() {
	*x = PlaceAskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceAskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceAskRequest) ProtoMessage() {}

func (x *PlaceAskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceAskRequest.ProtoReflect.Descriptor instead.
func (*PlaceAskRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_secondary_marketplace_secondary_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceAskRequest) GetAsk() *marketplace_common.Ask {
	if x != nil {
		return x.Ask
	}
	return nil
}

type PlaceAskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AskStatus *marketplace_common.AskStatus `protobuf:"bytes,1,opt,name=ask_status,json=askStatus,proto3" json:"ask_status,omitempty"`
}

func (x *PlaceAskResponse) Reset() {
	*x = PlaceAskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceAskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceAskResponse) ProtoMessage() {}

func (x *PlaceAskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_secondary_marketplace_secondary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceAskResponse.ProtoReflect.Descriptor instead.
func (*PlaceAskResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_secondary_marketplace_secondary_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceAskResponse) GetAskStatus() *marketplace_common.AskStatus {
	if x != nil {
		return x.AskStatus
	}
	return nil
}

var File_marketplace_secondary_marketplace_secondary_proto protoreflect.FileDescriptor

var file_marketplace_secondary_marketplace_secondary_proto_rawDesc = []byte{
	0x0a, 0x31, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x1a, 0x2b, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x62, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x64,
	0x52, 0x03, 0x62, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x69,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x62, 0x69, 0x64,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x62, 0x69,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3c, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x41, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x73,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x73, 0x6b,
	0x52, 0x03, 0x61, 0x73, 0x6b, 0x22, 0x50, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x61, 0x73, 0x6b,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x41, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xd0, 0x01, 0x0a, 0x14, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79,
	0x12, 0x5b, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x69, 0x64, 0x12, 0x26, 0x2e, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x2e, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a,
	0x08, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x73, 0x6b, 0x12, 0x26, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72,
	0x79, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41,
	0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x69, 0x64, 0x64, 0x2f, 0x66,
	0x72, 0x61, 0x63, 0x74, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_marketplace_secondary_marketplace_secondary_proto_rawDescOnce sync.Once
	file_marketplace_secondary_marketplace_secondary_proto_rawDescData = file_marketplace_secondary_marketplace_secondary_proto_rawDesc
)

func file_marketplace_secondary_marketplace_secondary_proto_rawDescGZIP() []byte {
	file_marketplace_secondary_marketplace_secondary_proto_rawDescOnce.Do(func() {
		file_marketplace_secondary_marketplace_secondary_proto_rawDescData = protoimpl.X.CompressGZIP(file_marketplace_secondary_marketplace_secondary_proto_rawDescData)
	})
	return file_marketplace_secondary_marketplace_secondary_proto_rawDescData
}

var file_marketplace_secondary_marketplace_secondary_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketplace_secondary_marketplace_secondary_proto_goTypes = []interface{}{
	(*PlaceBidRequest)(nil),              // 0: marketplace_secondary.PlaceBidRequest
	(*PlaceBidResponse)(nil),             // 1: marketplace_secondary.PlaceBidResponse
	(*PlaceAskRequest)(nil),              // 2: marketplace_secondary.PlaceAskRequest
	(*PlaceAskResponse)(nil),             // 3: marketplace_secondary.PlaceAskResponse
	(*marketplace_common.Bid)(nil),       // 4: marketplace_common.Bid
	(*marketplace_common.BidStatus)(nil), // 5: marketplace_common.BidStatus
	(*marketplace_common.Ask)(nil),       // 6: marketplace_common.Ask
	(*marketplace_common.AskStatus)(nil), // 7: marketplace_common.AskStatus
}
var file_marketplace_secondary_marketplace_secondary_proto_depIdxs = []int32{
	4, // 0: marketplace_secondary.PlaceBidRequest.bid:type_name -> marketplace_common.Bid
	5, // 1: marketplace_secondary.PlaceBidResponse.bid_status:type_name -> marketplace_common.BidStatus
	6, // 2: marketplace_secondary.PlaceAskRequest.ask:type_name -> marketplace_common.Ask
	7, // 3: marketplace_secondary.PlaceAskResponse.ask_status:type_name -> marketplace_common.AskStatus
	0, // 4: marketplace_secondary.MarketplaceSecondary.PlaceBid:input_type -> marketplace_secondary.PlaceBidRequest
	2, // 5: marketplace_secondary.MarketplaceSecondary.PlaceAsk:input_type -> marketplace_secondary.PlaceAskRequest
	1, // 6: marketplace_secondary.MarketplaceSecondary.PlaceBid:output_type -> marketplace_secondary.PlaceBidResponse
	3, // 7: marketplace_secondary.MarketplaceSecondary.PlaceAsk:output_type -> marketplace_secondary.PlaceAskResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_marketplace_secondary_marketplace_secondary_proto_init() }
func file_marketplace_secondary_marketplace_secondary_proto_init() {
	if File_marketplace_secondary_marketplace_secondary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marketplace_secondary_marketplace_secondary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceBidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketplace_secondary_marketplace_secondary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceBidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketplace_secondary_marketplace_secondary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceAskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketplace_secondary_marketplace_secondary_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceAskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marketplace_secondary_marketplace_secondary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_secondary_marketplace_secondary_proto_goTypes,
		DependencyIndexes: file_marketplace_secondary_marketplace_secondary_proto_depIdxs,
		MessageInfos:      file_marketplace_secondary_marketplace_secondary_proto_msgTypes,
	}.Build()
	File_marketplace_secondary_marketplace_secondary_proto = out.File
	file_marketplace_secondary_marketplace_secondary_proto_rawDesc = nil
	file_marketplace_secondary_marketplace_secondary_proto_goTypes = nil
	file_marketplace_secondary_marketplace_secondary_proto_depIdxs = nil
}
